let entries = {
    season1: {
        'season': 'Season 1996',
        'country': 'Peru',
        'club': 'Deportivo Pesquero',
        'year': '1996',
        'mainImage': 'alianza.png'
    },
    
    season2: {
        'season': 'Season 1997',
        'country': 'Peru',
        'club': 'Deportivo Pesquero',
        'year': '1997',
        'mainImage': 'alianza.png'
    },
    
    season3: {
        'season': 'Season 1998',
        'country': 'Peru',
        'club': 'Alianza Lima',
        'year': '1998',
        'mainImage': 'alianza.png'
    },
    
    season4: {
        'season': 'Season 1999',
        'country': 'Peru',
        'club': 'Alianza Lima',
        'year': '1999',
        'mainImage': 'alianza.png'
    },
    
    season5: {
        'season': 'Season 1999 - 2000',
        'country': 'Germany',
        'club': 'Werder Bremen',
        'year': '1999 - 2000',
        'mainImage': 'werder1999.png',
        'matches': {
            entry1: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-08-28.',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Hertha BSC',
                'inGameOnMin': '58',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '32',
                'redCard': '',
                'result': '1:1 ',
                'yellowCard': ''
            },
            entry2: {
                'assists': '1',
                'away': '1.FC Kaiserlautern',
                'date': '1999-09-12',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '5:0 ',
                'yellowCard': ''
            },
            entry3: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-09-19',
                'doubleYellowCard': '',
                'goals': '3',
                'home': 'VfL Wolfsburg',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:7 ',
                'yellowCard': ''
            },
            entry4: {
                'assists': '',
                'away': 'SSV Ulm 1846',
                'date': '1999-09-25',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:2 ',
                'yellowCard': ''
            },
            entry5: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-10-03',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'SC Freiburg',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:1 ',
                'yellowCard': ''
            },
            entry6: {
                'assists': '1',
                'away': '1860 Munich',
                'date': '1999-10-16',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '1:3 ',
                'yellowCard': ''
            },
            entry7: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-10-24',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Bor. Dortmund',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '1:3 ',
                'yellowCard': ''
            },
            entry8: {
                'assists': '',
                'away': 'Hansa Rostock',
                'date': '1999-10-29',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:1 ',
                'yellowCard': ''
            },
            entry9: {
                'assists': '',
                'away': 'E. Frankfurt',
                'date': '1999-11-19',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '3:1 ',
                'yellowCard': ''
            },
            entry10: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-11-07',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Arm. Bielefeld',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:2 ',
                'yellowCard': ''
            },
            entry11: {
                'assists': '',
                'away': 'Hamburger SV',
                'date': '1999-11-28',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:1 ',
                'yellowCard': ''
            },
            entry12: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-12-04',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Bay. Leverkusen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '3:2 ',
                'yellowCard': ''
            },
            entry13: {
                'assists': '1',
                'away': 'Unterhaching',
                'date': '1999-12-10',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:2 ',
                'yellowCard': ''
            },
            entry14: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-12-14',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'MSV Duisburg',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '0:1 ',
                'yellowCard': '1'
            },
            entry15: {
                'assists': '',
                'away': 'Bayern Munich',
                'date': '1999-12-17',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '0:2 ',
                'yellowCard': '1'
            },
            entry16: {
                'assists': '',
                'away': 'VfB Stuttgart',
                'date': '2000-02-05',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:1 ',
                'yellowCard': '1'
            },
            entry17: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-02-08',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'FC Schalke 04',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '3:1 ',
                'yellowCard': ''
            },
            entry18: {
                'assists': '',
                'away': 'Hertha BSC',
                'date': '2000-02-11',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '75',
                'ownGoal': '',
                'playedMinutes': '75',
                'redCard': '',
                'result': '4:1 ',
                'yellowCard': ''
            },
            entry19: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-02-19',
                'doubleYellowCard': '',
                'goals': '',
                'home': '1.FC Kaiserlautern',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '4:3 ',
                'yellowCard': ''
            },
            entry20: {
                'assists': '',
                'away': 'VfL Wolfsburg',
                'date': '2000-02-26',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:2 ',
                'yellowCard': ''
            },
            entry21: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-03-05',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'SSV Ulm 1846',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:1 ',
                'yellowCard': '1'
            },
            entry22: {
                'assists': '1',
                'away': 'SC Freiburg',
                'date': '2000-03-12',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '5:2 ',
                'yellowCard': ''
            },
            entry23: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-03-19',
                'doubleYellowCard': '',
                'goals': '',
                'home': '1860 Munich',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '1:0 ',
                'yellowCard': ''
            },
            entry24: {
                'assists': '',
                'away': 'Bor. Dortmund',
                'date': '2000-03-26',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '3:2 ',
                'yellowCard': ''
            },
            entry25: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-04-02',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Hansa Rostock',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '1:1 ',
                'yellowCard': ''
            },
            entry26: {
                'assists': '',
                'away': 'Arm. Bielefeld',
                'date': '2000-04-09',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '3:1 ',
                'yellowCard': ''
            },
            entry27: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-04-12',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'E. Frankfurt',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '1:0 ',
                'yellowCard': ''
            },
            entry28: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-04-15',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Hamburger SV',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '0:0 ',
                'yellowCard': '1'
            },
            entry29: {
                'assists': '',
                'away': 'Bay. Leverkusen',
                'date': '2000-04-20',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '1:3 ',
                'yellowCard': ''
            },
            entry30: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-04-30',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Unterhaching',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '1:0 ',
                'yellowCard': ''
            },
            entry31: {
                'assists': '1',
                'away': 'MSV Duisburg',
                'date': '2000-05-13',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '64',
                'ownGoal': '',
                'playedMinutes': '64',
                'redCard': '',
                'result': '4:0 ',
                'yellowCard': ''
            },
            entry32: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-05-20',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Bayern Munich',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '3:1 ',
                'yellowCard': ''
            }
        }
    },
    season6: {
        'season'    : 'Season 2000 - 2001',
        'country'   : 'Germany',
        'club'      : 'Werder Bremen',
        'year'      : '2000 - 2001',
        'mainImage' : 'werder1999.png',
        'matches'   : {
            entry1: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-08-28',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Hertha BSC',
                'inGameOnMin': '58',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '32',
                'redCard': '',
                'result': '1:1 ',
                'yellowCard': ''
            },
            entry2: {
                'assists': '1',
                'away': '1.FC Kaiserlautern',
                'date': '1999-09-12',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '5:0 ',
                'yellowCard': ''
            },
            entry3: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-09-19',
                'doubleYellowCard': '',
                'goals': '3',
                'home': 'VfL Wolfsburg',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:7 ',
                'yellowCard': ''
            },
            entry4: {
                'assists': '',
                'away': 'SSV Ulm 1846',
                'date': '1999-09-25',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:2 ',
                'yellowCard': ''
            },
            entry5: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-10-03',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'SC Freiburg',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:1 ',
                'yellowCard': ''
            },
            entry6: {
                'assists': '1',
                'away': '1860 Munich',
                'date': '1999-10-16',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '1:3 ',
                'yellowCard': ''
            },
            entry7: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-10-24',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Bor. Dortmund',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '1:3 ',
                'yellowCard': ''
            },
            entry8: {
                'assists': '',
                'away': 'Hansa Rostock',
                'date': '1999-10-29',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:1 ',
                'yellowCard': ''
            },
            entry9: {
                'assists': '',
                'away': 'E. Frankfurt',
                'date': '1999-11-19',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '3:1 ',
                'yellowCard': ''
            },
            entry10: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-11-07',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Arm. Bielefeld',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:2 ',
                'yellowCard': ''
            },
            entry11: {
                'assists': '',
                'away': 'Hamburger SV',
                'date': '1999-11-28',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:1 ',
                'yellowCard': ''
            },
            entry12: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-12-04',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Bay. Leverkusen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '3:2 ',
                'yellowCard': ''
            },
            entry13: {
                'assists': '1',
                'away': 'Unterhaching',
                'date': '1999-12-10',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:2 ',
                'yellowCard': ''
            },
            entry14: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '1999-12-14',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'MSV Duisburg',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '0:1 ',
                'yellowCard': '1'
            },
            entry15: {
                'assists': '',
                'away': 'Bayern Munich',
                'date': '1999-12-17',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '0:2 ',
                'yellowCard': '1'
            },
            entry16: {
                'assists': '',
                'away': 'VfB Stuttgart',
                'date': '2000-02-05',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:1 ',
                'yellowCard': '1'
            },
            entry17: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-02-08',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'FC Schalke 04',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '3:1 ',
                'yellowCard': ''
            },
            entry18: {
                'assists': '',
                'away': 'Hertha BSC',
                'date': '2000-02-11',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '75',
                'ownGoal': '',
                'playedMinutes': '75',
                'redCard': '',
                'result': '4:1 ',
                'yellowCard': ''
            },
            entry19: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-02-19',
                'doubleYellowCard': '',
                'goals': '',
                'home': '1.FC Kaiserlautern',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '4:3 ',
                'yellowCard': ''
            },
            entry20: {
                'assists': '',
                'away': 'VfL Wolfsburg',
                'date': '2000-02-26',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:2 ',
                'yellowCard': ''
            },
            entry21: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-03-05',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'SSV Ulm 1846',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '2:1 ',
                'yellowCard': '1'
            },
            entry22: {
                'assists': '1',
                'away': 'SC Freiburg',
                'date': '2000-03-12',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '5:2 ',
                'yellowCard': ''
            },
            entry23: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-03-19',
                'doubleYellowCard': '',
                'goals': '',
                'home': '1860 Munich',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '1:0 ',
                'yellowCard': ''
            },
            entry24: {
                'assists': '',
                'away': 'Bor. Dortmund',
                'date': '2000-03-26',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '3:2 ',
                'yellowCard': ''
            },
            entry25: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-04-02',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Hansa Rostock',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '1:1 ',
                'yellowCard': ''
            },
            entry26: {
                'assists': '',
                'away': 'Arm. Bielefeld',
                'date': '2000-04-09',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '3:1 ',
                'yellowCard': ''
            },
            entry27: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-04-12',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'E. Frankfurt',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '1:0 ',
                'yellowCard': ''
            },
            entry28: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-04-15',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Hamburger SV',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '0:0 ',
                'yellowCard': '1'
            },
            entry29: {
                'assists': '',
                'away': 'Bay. Leverkusen',
                'date': '2000-04-20',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '',
                'redCard': '',
                'result': '1:3 ',
                'yellowCard': ''
            },
            entry30: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-04-30',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Unterhaching',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '1:0 ',
                'yellowCard': ''
            },
            entry31: {
                'assists': '1',
                'away': 'MSV Duisburg',
                'date': '2000-05-13',
                'doubleYellowCard': '',
                'goals': '1',
                'home': 'Werder Bremen',
                'inGameOnMin': '',
                'outGameOnMin': '64',
                'ownGoal': '',
                'playedMinutes': '64',
                'redCard': '',
                'result': '4:0 ',
                'yellowCard': ''
            },
            entry32: {
                'assists': '',
                'away': 'Werder Bremen',
                'date': '2000-05-20',
                'doubleYellowCard': '',
                'goals': '',
                'home': 'Bayern Munich',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'ownGoal': '',
                'playedMinutes': '90',
                'redCard': '',
                'result': '3:1 ',
                'yellowCard': ''
            }
        }
    },
    season7: {
        'season'    : 'Season 2001 - 2002',
        'country'   : 'Germany',
        'club'      : 'Bayern Munich',
        'year'      : '2001 - 2002',
        'mainImage' : 'bayern2014.png',
        'matches'   : {
            'entry1': {
                'date': '2001.07.28',
                'home': 'Bor. Monchengladbach',
                'away': 'Bayern Munich',
                'result': '1:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': ''
            },
            'entry2': {
                'date': '2001.08.04',
                'home': 'Bayern Munich',
                'away': 'FC Schalke 04',
                'result': '3:0 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '85',
                'playedMinutes': '85'
            },
            'entry3': {
                'date': '2001.08.11',
                'home': 'Bay. Leverkusen',
                'away': 'Bayern Munich',
                'result': '1:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '7',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry4': {
                'date': '2001.08.18',
                'home': 'Bayern Munich',
                'away': 'FC St. Pauli',
                'result': '2:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': ''
            },
            'entry5': {
                'date': '2001.09.08',
                'home': 'Bor. Dortmund',
                'away': 'Bayern Munich',
                'result': '0:2 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '78',
                'outGameOnMin': '',
                'playedMinutes': '12'
            },
            'entry6': {
                'date': '2001.09.15',
                'home': 'Bayern Munich',
                'away': 'SC Freiburg',
                'result': '1:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry7': {
                'date': '2001.09.22',
                'home': 'Energie Cottbus',
                'away': 'Bayern Munich',
                'result': '0:3 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry8': {
                'date': '2001.09.30',
                'home': 'Bayern Munich',
                'away': 'VfB Stuttgart',
                'result': '4:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry9': {
                'date': '2001.10.13',
                'home': '1860 Munich',
                'away': 'Bayern Munich',
                'result': '1:5 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '75',
                'outGameOnMin': '',
                'playedMinutes': '15'
            },
            'entry10': {
                'date': '2001.10.20',
                'home': 'Bayern Munich',
                'away': '1.FC Kaiserlautern',
                'result': '4:1 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '69',
                'outGameOnMin': '',
                'playedMinutes': '21'
            },
            'entry11': {
                'date': '2001.10.27',
                'home': '1.FC Koeln',
                'away': 'Bayern Munich',
                'result': '0:2 ',
                'goals': '2',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '90',
                'playedMinutes': '90'
            },
            'entry12': {
                'date': '2001.11.03',
                'home': 'Bayern Munich',
                'away': 'Hamburger SV',
                'result': '3:0 ',
                'goals': '2',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry13': {
                'date': '2001.11.17',
                'home': 'Werder Bremen',
                'away': 'Bayern Munich',
                'result': '1:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry14': {
                'date': '2001.11.24',
                'home': 'Bayern Munich',
                'away': '1.FC Nuernberg',
                'result': '0:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '70',
                'playedMinutes': '70'
            },
            'entry15': {
                'date': '2001.12.02',
                'home': 'Hertha BSC',
                'away': 'Bayern Munich',
                'result': '2:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '73',
                'outGameOnMin': '',
                'playedMinutes': '17'
            },
            'entry16': {
                'date': '2001.12.08',
                'home': 'Bayern Munich',
                'away': 'VfL Wolfsburg',
                'result': '3:3 ',
                'goals': '2',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '69',
                'playedMinutes': '69'
            },
            'entry17': {
                'date': '2001.12.15',
                'home': 'Hansa Rostock',
                'away': 'Bayern Munich',
                'result': '1:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry18': {
                'date': '2001.12.18',
                'home': 'Bayern Munich',
                'away': 'Bor. Monchengladbach',
                'result': '0:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry19': {
                'date': '2002.01.26',
                'home': 'FC Schalke 04',
                'away': 'Bayern Munich',
                'result': '5:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '68',
                'outGameOnMin': '',
                'playedMinutes': '22'
            },
            'entry20': {
                'date': '2002.02.03',
                'home': 'Bayern Munich',
                'away': 'Bay. Leverkusen',
                'result': '2:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '78',
                'outGameOnMin': '',
                'playedMinutes': '12'
            },
            'entry21': {
                'date': '2002.02.06',
                'home': 'FC St. Pauli',
                'away': 'Bayern Munich',
                'result': '2:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry22': {
                'date': '2002.02.09',
                'home': 'Bayern Munich',
                'away': 'Bor. Dortmund',
                'result': '1:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '75',
                'outGameOnMin': '',
                'playedMinutes': '15'
            },
            'entry23': {
                'date': '2002.02.16',
                'home': 'SC Freiburg',
                'away': 'Bayern Munich',
                'result': '0:2 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '82',
                'outGameOnMin': '',
                'playedMinutes': '8'
            },
            'entry24': {
                'date': '2002.02.23',
                'home': 'Bayern Munich',
                'away': 'Energie Cottbus',
                'result': '6:0 ',
                'goals': '2',
                'assists': '2',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry25': {
                'date': '2002.03.02',
                'home': 'VfB Stuttgart',
                'away': 'Bayern Munich',
                'result': '0:2 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '69',
                'outGameOnMin': '',
                'playedMinutes': '21'
            },
            'entry26': {
                'date': '2002.03.09',
                'home': 'Bayern Munich',
                'away': '1860 Munich',
                'result': '2:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '67',
                'outGameOnMin': '',
                'playedMinutes': '23'
            },
            'entry27': {
                'date': '2002.03.16',
                'home': '1.FC Kaiserlautern',
                'away': 'Bayern Munich',
                'result': '0:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '76',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '46',
                'outGameOnMin': '',
                'playedMinutes': '45'
            },
            'entry28': {
                'date': '2002.03.23',
                'home': 'Bayern Munich',
                'away': '1.FC Köln',
                'result': '3:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': ''
            },
            'entry29': {
                'date': '2002.03.30',
                'home': 'Hamburger SV',
                'away': 'Bayern Munich',
                'result': '0:0 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '71',
                'outGameOnMin': '',
                'playedMinutes': '19'
            },
            'entry30': {
                'date': '2002.04.06',
                'home': 'Bayern Munich',
                'away': 'Werder Bremen',
                'result': '2:2 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry31': {
                'date': '2002.04.13',
                'home': '1.FC Nürnberg',
                'away': 'Bayern Munich',
                'result': '1:2 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry32': {
                'date': '2002.04.20',
                'home': 'Bayern Munich',
                'away': 'Hertha BSC',
                'result': '3:0 ',
                'goals': '1',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '86',
                'playedMinutes': '86'
            },
            'entry33': {
                'date': '2002.04.27',
                'home': 'VfL Wolfsburg',
                'away': 'Bayern Munich',
                'result': '0:1 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '3',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': '90'
            },
            'entry34': {
                'date': '2002.05.04',
                'home': 'Bayern Munich',
                'away': 'Hansa Rostock',
                'result': '3:2 ',
                'goals': '',
                'assists': '',
                'ownGoal': '',
                'yellowCard': '',
                'doubleYellowCard': '',
                'redCard': '',
                'inGameOnMin': '',
                'outGameOnMin': '',
                'playedMinutes': ''
            }
        }
    }
};


export default entries;